# Generated by Django 4.0.6 on 2022-08-02 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_language'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Language',
        ),
    ]
