# Generated by Django 4.0.6 on 2022-08-06 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_alter_bookinstance_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['title', 'imprint']},
        ),
        migrations.RemoveField(
            model_name='bookinstance',
            name='imprint',
        ),
        migrations.RemoveField(
            model_name='bookinstance',
            name='isbn',
        ),
        migrations.AddField(
            model_name='book',
            name='imprint',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='isbn',
            field=models.CharField(help_text='13 Character <a href="https://www.isbn-international.org/content/what-isbn">ISBN number</a>', max_length=13, null=True, verbose_name='ISBN'),
        ),
    ]
