# Generated by Django 4.0.6 on 2022-08-06 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_alter_book_options_remove_bookinstance_imprint_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='image',
            field=models.ImageField(default='static/img/default.jpg', upload_to='book'),
        ),
    ]
