# Generated by Django 4.0.6 on 2022-08-09 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_author_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='summary',
            field=models.TextField(default='暂无简介', help_text='Enter a brief description of the author', max_length=1000),
        ),
        migrations.AlterField(
            model_name='author',
            name='image',
            field=models.ImageField(default='author/default.jpg', upload_to='author'),
        ),
        migrations.AlterField(
            model_name='book',
            name='image',
            field=models.ImageField(default='book/default.jpg', upload_to='book'),
        ),
    ]
